-- Generated by theme-set — do not edit. Source: themes/templates/hypr-colors.lua
-- Required by hyprland.lua (borders + shadow follow the palette).
hl.config({
    general = {
        col = {
            active_border   = { colors = { "rgba({{accent_hex}}ff)", "rgba({{accent2_hex}}ff)" }, angle = 45 },
            inactive_border = "rgba({{surface2_hex}}cc)",
        },
    },
    decoration = {
        -- shadow tint follows the palette background
        shadow = {
            color = 0x99{{bg_hex}},
        },
    },
})
