-- Generated by theme-set — do not edit. Source: themes/templates/nvim-palette.lua
-- Maps the canonical palette to the role names used by lua/config/colors.lua.
return {
  bg = "{{bg}}",
  fg = "{{fg}}",

  comment = "{{muted}}",
  keyword = "{{accent}}",
  func = "{{accent2}}",
  type = "{{info}}",
  string = "{{string}}",
  number = "{{number}}",
  special = "{{ok}}",
  namespace = "{{namespace}}",

  operator = "{{color7}}",
  delimiter = "{{muted}}",

  warn = "{{warn}}",
  error = "{{error}}",
  info = "{{info}}",
  hint = "{{ok}}",

  ui0 = "{{surface0}}",
  ui1 = "{{surface1}}",
  ui2 = "{{surface2}}",
  ui3 = "{{surface3}}",
}
