--------------------------------------------------------------------------------
--  Hyprland (Lua config, 0.55+) — managed by dotfiles.
--  Per-host bits live in env.lua / monitors.lua; colors in colors.lua (theme-set).
--------------------------------------------------------------------------------

-- Per-host + generated modules (~/.config/hypr/<name>.lua).
-- Hyprland's require() already reports errors *inside* a module without
-- aborting the config, but a *missing* file raises — pcall keeps the session
-- usable (default monitors/colors) until install.sh / theme-set create them.
local function optional(name)
    local ok, err = pcall(require, name)
    if not ok then print("hyprland.lua: skipping " .. name .. ": " .. tostring(err)) end
end
optional("env")        -- GPU / Wayland env (NVIDIA etc.); empty on other hosts
optional("monitors")   -- monitor layout (generated by install.sh)
optional("colors")     -- palette borders + shadow (rendered by theme-set)

-- --- global env --------------------------------------------------------------
hl.env("XCURSOR_THEME", "Bibata-Modern-Ice")
hl.env("XCURSOR_SIZE", "24")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")

-- --- autostart ---------------------------------------------------------------
hl.on("hyprland.start", function()
    hl.exec_cmd("waybar")
    hl.exec_cmd("swaync")
    hl.exec_cmd("systemctl --user start hyprpolkitagent")
    -- network + bluetooth are handled by the waybar modules (rofi wifi menu /
    -- blueman-manager); the tray applets only duplicated them.
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("hypridle")
    -- restore the last theme (wallpaper + colors); also starts the wallpaper daemon
    hl.exec_cmd("~/.local/bin/theme-set \"$(cat ~/.cache/theme/current 2>/dev/null || echo cafe)\"")
    -- terminal on login
    hl.exec_cmd("kitty")
end)

-- --- input -------------------------------------------------------------------
hl.config({
    input = {
        kb_layout    = "pl",
        kb_options   = "caps:escape",
        follow_mouse = 1,
        sensitivity  = 0,
        touchpad = {
            natural_scroll = false,
        },
    },
})

-- --- look & feel -------------------------------------------------------------
hl.config({
    general = {
        gaps_in          = 4,
        gaps_out         = 10,
        border_size      = 2,
        layout           = "dwindle",
        resize_on_border = true,
        -- border colors set in colors.lua (theme-set)
    },

    decoration = {
        rounding         = 12,
        active_opacity   = 1.0,
        inactive_opacity = 0.96,
        blur = {
            enabled           = true,
            size              = 5,
            passes            = 2,
            new_optimizations = true,
            ignore_opacity    = true,
            vibrancy          = 0.15,
            noise             = 0.01,
        },
        shadow = {
            enabled      = true,
            range        = 18,
            render_power = 3,
            -- color set in colors.lua (theme-set)
        },
    },

    dwindle = {
        preserve_split = true,
    },

    misc = {
        disable_hyprland_logo   = true,
        disable_splash_rendering = true,
        force_default_wallpaper = 0,
    },

    animations = {
        enabled = true,
    },
})

-- --- animations (your curves, kept) -----------------------------------------
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1} } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1} } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1} } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1.0} } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1} } })

hl.animation({ leaf = "global",       enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",       enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",      enabled = true, speed = 4.79, bezier = "easeOutQuint" })
hl.animation({ leaf = "windowsIn",    enabled = true, speed = 4.1,  bezier = "easeOutQuint", style = "popin 87%" })
hl.animation({ leaf = "windowsOut",   enabled = true, speed = 1.49, bezier = "linear",       style = "popin 87%" })
hl.animation({ leaf = "fadeIn",       enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",      enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",         enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",       enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",     enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",    enabled = true, speed = 1.5,  bezier = "linear",       style = "fade" })
hl.animation({ leaf = "workspaces",   enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut",enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })

-- --- keybindings (ported from your setup) -----------------------------------
local mod = "SUPER"

hl.bind(mod .. " + Return",     hl.dsp.exec_cmd("kitty"))
hl.bind(mod .. " + C",          hl.dsp.window.close())
hl.bind(mod .. " + F",          hl.dsp.window.fullscreen({ action = "toggle" }))
hl.bind(mod .. " + SPACE",      hl.dsp.exec_cmd("rofi -show drun"))
hl.bind(mod .. " + B",          hl.dsp.exec_cmd("brave --disable-features=WaylandWpColorManagerV1"))
hl.bind(mod .. " + D",          hl.dsp.exec_cmd("discord"))
hl.bind(mod .. " + N",          hl.dsp.exec_cmd("nautilus"))
hl.bind(mod .. " + L",          hl.dsp.exec_cmd("hyprlock"))
hl.bind(mod .. " + O",          hl.dsp.exec_cmd("obsidian"))
hl.bind(mod .. " + V",          hl.dsp.window.float({ action = "toggle" }))
hl.bind(mod .. " + P",          hl.dsp.exec_cmd("cliphist list | rofi -dmenu | cliphist decode | wl-copy"))
-- lock / logout / suspend / reboot / shutdown (also the waybar power button)
hl.bind(mod .. " + SHIFT + E",  hl.dsp.exec_cmd("~/.local/bin/power-menu"))

-- theme / wallpaper picker (SUPER+W is a workspace, so the picker is on T)
hl.bind(mod .. " + T",          hl.dsp.exec_cmd("~/.local/bin/wallpaper-picker"))

-- workspaces (1,2,3 then Q,W,E)
local workspaces = { ["1"] = 1, ["2"] = 2, ["3"] = 3, Q = 4, W = 5, E = 6 }
for key, n in pairs(workspaces) do
    hl.bind(mod .. " + " .. key,         hl.dsp.focus({ workspace = n }))
    hl.bind(mod .. " + SHIFT + " .. key, hl.dsp.window.move({ workspace = n }))
end
hl.bind(mod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(mod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- move / resize with mouse
hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- focus / swap windows with arrows (+CTRL resizes, below)
for _, dir in ipairs({ "left", "right", "up", "down" }) do
    hl.bind(mod .. " + " .. dir,         hl.dsp.focus({ direction = dir }))
    hl.bind(mod .. " + SHIFT + " .. dir, hl.dsp.window.swap({ direction = dir }))
end

-- precise keyboard resize
hl.bind(mod .. " + CTRL + left",  hl.dsp.window.resize({ x = -50, y = 0,  relative = true }))
hl.bind(mod .. " + CTRL + right", hl.dsp.window.resize({ x = 50,  y = 0,  relative = true }))
hl.bind(mod .. " + CTRL + up",    hl.dsp.window.resize({ x = 0,   y = -50, relative = true }))
hl.bind(mod .. " + CTRL + down",  hl.dsp.window.resize({ x = 0,   y = 50,  relative = true }))

-- media / brightness keys (locked = works on lockscreen, repeating = key repeat)
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"),  { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),  { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioPlay",        hl.dsp.exec_cmd("playerctl play-pause"),                       { locked = true })
hl.bind("XF86AudioNext",        hl.dsp.exec_cmd("playerctl next"),                             { locked = true })
hl.bind("XF86AudioPrev",        hl.dsp.exec_cmd("playerctl previous"),                         { locked = true })
hl.bind("XF86MonBrightnessUp",   hl.dsp.exec_cmd("brightnessctl set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl set 5%-"), { locked = true, repeating = true })

-- screenshots
hl.bind("Print",                hl.dsp.exec_cmd("grim ~/Pictures/screenshot_$(date +'%Y-%m-%d_%H-%M-%S').png"))
hl.bind("SHIFT + Print",        hl.dsp.exec_cmd("slurp | grim -g - ~/Pictures/screenshot_$(date +'%Y-%m-%d_%H-%M-%S').png"))
hl.bind(mod .. " + Print",         hl.dsp.exec_cmd("slurp | grim -g - - | wl-copy"))
hl.bind(mod .. " + SHIFT + Print", hl.dsp.exec_cmd("slurp | grim -g - - | swappy -f -"))

-- --- window rules ------------------------------------------------------------
hl.window_rule({ name = "float-pavucontrol",        match = { class = "^(pavucontrol)$" },        float = true })
hl.window_rule({ name = "float-blueman-manager",    match = { class = "^(blueman-manager)$" },     float = true })
hl.window_rule({ name = "float-nm-connection-editor", match = { class = "^(nm-connection-editor)$" }, float = true })
